### ISSUE TITLE
Change useHooks to something else

### ISSUE THREAD

**Issue by Brooooooklyn** [LeetCode-OpenSource/ayanami#16]
`use` means hooks already. `useHooks` looks too verbose.

**Comment by Runjuu** [comment]
Just an idea, we could split `useHooks` into two hooks methods. One is `useState` and the other is `useAction`. The advantage is that if there is an `FC` just needs to trigger action. Use `useAction` can avoid unnecessarily re-render. Does anyone have any idea?

**Comment by Runjuu** [comment]
fix at release 0.10.0
