### ISSUE TITLE
希望effects异步执行完毕能提供回调

### ISSUE THREAD

**Issue by wangmingxu** [LeetCode-OpenSource/ayanami#49]
现在有比较多的场景都需要effects执行完毕的回调，比如loading,编辑弹窗完成后异步提交结束后关闭弹窗，但是现在的异步actions执行的结果的undefined,无法获取执行完毕的回调，需要通过设置额外的state来标示，然后通过判断state的变化来执行对应的操作，每个类都需要写一遍，感觉有点复杂

**Comment by Brooooooklyn** [comment]
我们不希望把 process management 的逻辑泄漏到 Component 里面，Component 应该总是通过数据驱动的。
你应该在组件层面思考如何**抽象** 你面临的这个问题，而不是简单的通过回调**命令式**的在 Component 里面编写与副作用控制逻辑**耦合**的逻辑
